language: php
php:
  - 7.1
before_script:
  - sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libgif-dev webp openjpeg-tools
  - wget https://github.com/ImageMagick/ImageMagick/archive/7.0.7-21.tar.gz
  - tar xzf 7.0.7-21.tar.gz
  - cd ImageMagick-7.0.7-21
  - ./configure --with-raw=yes 
  - sudo make
  - sudo make install
  - cd ..
  - printf "\n" | pecl install imagick
  - travis_retry composer self-update --preview
  - travis_retry composer install --prefer-dist --no-interaction
script:
  - bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
